include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

linter:
  rules:
    # # https://dart.dev/tools/linter-rules#prefer_double_quotes
    # - prefer_double_quotes
    # # https://dart.dev/tools/linter-rules#prefer_null_aware_operators
    # - prefer_null_aware_method_calls
